# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e6e2d8f60f9682ad4d66bce14c282e60998dea7a2ad08c9c619ce52231e9d30defd2b81f46da01dec3159ef32f1aa4abac0bbde78119b20d9f63aa848b86971

test:
  secret_key_base: ed082b11ee1cb6e721b31b543232418be974e7194ba643c7720d176f5eb8db84f239356435cf142772cb22d466d0cffb9d1311ab5ae253f8f2b7be3f570324f3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
